CREATE TABLE IF NOT EXISTS results (
  id serial NOT NULL,
  nume text NOT NULL,
  prenume text NOT NULL,
  scoala text NOT NULL,
  judet text NOT NULL,
  promotie_anterioara text NOT NULL,
  forma_invatamant text NOT NULL,
  specializare text NOT NULL,
  calificativ_competente_romana text,
  nota_romana decimal NOT NULL,
  nota_romana_contestatie decimal,
  nota_romana_final decimal NOT NULL,
  limba_materna text,
  limba_moderna text NOT NULL,
  nota_limba_moderna text,
  disciplina_obligatorie text NOT NULL,
  disciplina_alegere text NOT NULL,
  competente_digitale text,
  medie decimal,
  rezultat_final text NOT NULL,
  calificativ_competente_materna text,
  nota_materna decimal,
  nota_materna_contestatie decimal,
  nota_materna_final decimal,
  nota_obligatorie decimal NOT NULL,
  nota_obligatorie_contestatie decimal,
  nota_obligatorie_final decimal NOT NULL,
  nota_alegere decimal NOT NULL,
  nota_alegere_contestatie decimal,
  nota_alegere_final decimal NOT NULL,
  PRIMARY KEY (id)
);
